### ISSUE TITLE
Maybe hold different semesters in different branches?

### ISSUE THREAD

**Issue by t0t07** [berkeley-cs186/project-gitbook#1]
For example, sp-2020 branch, fa-2020 branch, etc.

So that it is easier to view.

**Comment by ckw017** [comment]
We've tagged the end of last semester, which should cover your needs. You can view the final version of the fa20 spec at https://github.com/berkeley-cs186/project-gitbook/tree/fa20

**Comment by t0t07** [comment]
thanks!
